name = "ProudPalettes"
uuid = "61d02e3d-8de9-45ce-a87b-73174b99cb55"
authors = ["Nathan Musoke <nathan.musoke@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Colors = "0.12.0"
PrecompileTools = "1.2.1"
julia = "1.6"
